### ISSUE TITLE
Update default zenodo record id to be able to get aer_v3.8.1.tar.gz in get_line_file.py

### ISSUE THREAD

**Issue by thieul** [AER-RC/AER_Line_File#3]
By conforming to the README file, it is not possible to get through zenodo the aer_v_3.8.1.tar.gz archive but rather the aer_v_3.8.tar.gz one because default zenodo record id in get_line_file.py match the one for aer_v3.8 .
That would be good to change the zenodo id from  4019086 to 5120012

**Comment by pernak18** [comment]
@thieul `get_line_file.py` has a `--record` input keyword, so there is flexibility with what record is downloaded. for 3.8.1:

```
./get_line_file.py -r 5120012
```

i agree, though -- the `README.md` is inaccurate and would benefit from explicit mention of the keyword. i've just updated with 1fb6e51e1a36f3238bd2c7fb9531dbb6b692c15b
